version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'monthly'
    assignees:
      - "chrisdchow"
    ignore:
      # Version 9+ is a pure ES module, requires refactoring ts-jest
      - dependency-name: "@lokalise/node-api"
      # Version 12+ is a pure ES module, requires refactoring ts-jest
      - dependency-name: "got"
