name: 'Lokalise Actions'
description: 'Upload and download files from Lokalise'
branding:
  icon: arrow-up-circle
  color: purple
author: 'Color Health'
inputs:
  action:
    description: Operation to perform (push, pull)
    required: true
  api-token:
    description: API token
    required: true
  project-id:
    description: The project ID
    required: true
  format:
    description: The file format of the translation files
    required: true
  translation-directory:
    description: The directory to find translation language files
    required: true
  replace-modified:
    description: Boolean, replace/update existing translation on upload
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
