name: 'Lokalise Actions'
description: 'Creates and archives Lokalise Keys as well as pull remote files.'
branding:
  icon: arrow-up-circle
  color: purple
author: 'Color Health'
inputs:
  api-token:
    description: API token
    required: true
  project-id:
    description: The project ID
    required: true
  format:
    description: The file format to parse. (json, properties)
    required: true
  platform:
    description: The Lokalise platform to sync
    required: true
  source-language:
    description: The locale of the source language
  source-language-directory:
    description: The directory to find source language files
  translation-directory:
    description: The directory to find translation language files
runs:
  using: 'node12'
  main: 'dist/index.js'
