name: dependabot validate

on:
  pull_request:
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/validate-dependabot.yml"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: marocchino/validate-dependabot@v1.1.1
        id: validate
      - uses: marocchino/sticky-pull-request-comment@v2.1.0
        if: always()
        with:
          header: validate-dependabot
          message: ${{ steps.validate.outputs.markdown }}
